sudo: required
services:
  - docker

before_install:
  - docker build -t intuit -f Dockerfile.dev .

script:
  - docker run -e CI=true intuit npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Intuit1"
  env: "Intuit1-env"
  bucket_name: "elasticbeanstalk-us-west-1-7715100094871"
  bucket_path: "Intuit1"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"