sudo: required
services:
  - docker

branches:
  only:
    - master
    - stable

before_install:
  - docker build -t intuit -f Dockerfile.dev .

script:
  - docker run intuit npm run test -- --coverage
