sudo: required
services:
  - docker

before_install:
  - docker build -t intuit -f Dockerfile.dev .

script:
  - docker run -e CI=true intuit npm run test

deploy:
  provider: s3
  edge:
    branch: master
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Intuit"
  env: "Intuit-env"
  bucket_name: "elasticbeanstalk-us-west-1-771510009487"
  bucket_path: "Intuit"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"