sudo: required
services:
  - docker

before_install:
  - docker build -t intuit -f Dockerfile.dev .

script:
  - docker run -e CI=true intuit npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "IntuitApp"
  env: "Intuitapp-env"
  bucket_name: "elasticbeanstalk-us-west-1-771510009487"
  bucket_path: "IntuitApp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"